name: workflow run cleanup
on: workflow_dispatch
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: clean workflow runs
        uses: boredland/action-purge-workflow-runs@main
        with:
          days-old: 1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_CLEANUP_PAT }}